### ISSUE TITLE
Regarding the sin_sq_exps.

### ISSUE THREAD

**Issue by zorrocai** [jihunchoi/lsoftmax-pytorch#2]
I think the line
`self.sin_sq_exps = range(len(self.cos_exps))`
should replaced by 
`self.sin_sq_exps = [self.margin - x for x in self.cos_exps].`

**Comment by amirhfarzaneh** [comment]
for a `margin=4` your solution will produce 0, 2, 4. But if you look at equation7 in the paper you will see that the powers for (1-cos^2(theta)) (i.e. sin^2(theta)) are a sequence like this: 0, 1, 2. So @jihunchoi 's solution is correct!

**Comment by zorrocai** [comment]
Yes, you are right.
